version: "3.8"
services:
  nginx:
    restart: always
    container_name: nginx
    image: ${{ secrets.DOCKER_NAME }}/mern_nginx:latest
    ports:
      - '80:80'
    depends_on:
      - client
      - api
    networks:
      - socialapp-network
  api:
    container_name: api
    image: ${{ secrets.DOCKER_NAME }}/mern_backend:latest
    environment:
      - MONGODB_URL=${{ secrets.DOCKER_NAME }}
      - JWT_SECRET=sample
      - PORT=5000
    networks:
      - socialapp-network
    restart: always
  client:
    container_name: client
    image: ${{ secrets.DOCKERHUB_NAME }}/mern_front:latest
    networks:
      - socialapp-network
    restart: always

networks:
  socialapp-network:
    
